//V2.0
// so i asked claude help to map all of the colors codes, so u don't really need to put the code in all of the colors, surely, you will have to search the internet if u want a flying chihuahua of the sahara desert blue, but the main colors are there
//u can still add colors just by following the pattern, so if u want to add the Goose Turd Green, just put the coma in the last array and add {"Goose Turd Green", 84, 255, 162, 255}
//V3.0
// the 3.0 code is almost all generated by claude, i'm sorry but i had no idea how to do that without it, don't judge me bro, i'm not god, genius or sum shi


#include <Adafruit_NeoPixel.h>
#include <Preferences.h>

#define LED_PIN 48
#define LED_COUNT 1

Adafruit_NeoPixel rgbLed(LED_COUNT, LED_PIN, NEO_GRB + NEO_KHZ800);
Preferences prefs;

struct NamedColor {
  char name[32];
  uint8_t r, g, b, brightness;
};

// default colors, always present
NamedColor defaultColors[] = {
  {"red",     255, 0,   0,   255},
  {"green",   0,   255, 0,   255},
  {"blue",    0,   0,   255, 255},
  {"yellow",  255, 255, 0,   255},
  {"cyan",    0,   255, 255, 255},
  {"magenta", 255, 0,   255, 255},
  {"white",   255, 255, 255, 255},
  {"orange",  255, 165, 0,   255},
  {"purple",  128, 0,   128, 255},  // <--- just like this
  {"off",     0,   0,   0,   255}   //add a coma here if u want to add another default color
};

#define MAX_CUSTOM 20
NamedColor customColors[MAX_CUSTOM];
int customCount = 0;

int defaultCount = sizeof(defaultColors) / sizeof(defaultColors[0]);

void toLowerStr(char* str) {
  for (int i = 0; str[i]; i++) {
    if (str[i] >= 'A' && str[i] <= 'Z') str[i] += 32;  //this block was a bitch to write, why so complicated, don't ask me how ts works
  }
}

void applyColor(uint8_t r, uint8_t g, uint8_t b, uint8_t bright) {
  rgbLed.setBrightness(bright);
  rgbLed.setPixelColor(0, rgbLed.Color(r, g, b));
  rgbLed.show();
}

void loadCustomColors() {
  prefs.begin("lce", true);
  customCount = prefs.getInt("count", 0);
  for (int i = 0; i < customCount; i++) {
    char key[16];
    sprintf(key, "c%d", i);
    prefs.getBytes(key, &customColors[i], sizeof(NamedColor));
  }
  prefs.end();
}

void saveCustomColors() {
  prefs.begin("lce", false);
  prefs.putInt("count", customCount);
  for (int i = 0; i < customCount; i++) {
    char key[16];
    sprintf(key, "c%d", i);
    prefs.putBytes(key, &customColors[i], sizeof(NamedColor));
  }
  prefs.end();
}

void listAllColors() {
  Serial.println("--- color list ---");
  for (int i = 0; i < defaultCount; i++) {
    Serial.print(i); Serial.print(". [default] "); Serial.println(defaultColors[i].name);
  }
  for (int i = 0; i < customCount; i++) {
    Serial.print(defaultCount + i); Serial.print(". "); Serial.println(customColors[i].name);
  }
  Serial.println("------------------");
}

NamedColor* getColorByIndex(int idx) {
  if (idx < defaultCount) return &defaultColors[idx];
  idx -= defaultCount;
  if (idx < customCount) return &customColors[idx];
  return nullptr;
}

// blocks waiting for serial input, returns length
int waitForInput(char* buf, int maxLen) {
  while (Serial.available() == 0) {}
  int len = Serial.readBytesUntil('\n', buf, maxLen - 1);
  buf[len] = '\0';
  if (len > 0 && buf[len-1] == '\r') buf[--len] = '\0';
  return len;
}

bool parseColor(char* input, uint8_t &r, uint8_t &g, uint8_t &b) {
  // hex
  if (input[0] == '#') {
    int ri, gi, bi;
    if (sscanf(input + 1, "%02x%02x%02x", &ri, &gi, &bi) == 3) {
      r = ri; g = gi; b = bi;
      return true;
    }
    return false;
  }
  // rgb(r g b)
  if (strncmp(input, "rgb(", 4) == 0) {
    int ri, gi, bi;
    if (sscanf(input + 4, "%d %d %d", &ri, &gi, &bi) == 3) {
      r = constrain(ri, 0, 255);
      g = constrain(gi, 0, 255);
      b = constrain(bi, 0, 255);
      return true;
    }
    return false;
  }
  return false;
}

uint8_t askBrightness() {
  Serial.print("Want to define brightness? Y/N: ");
  char buf[8];
  waitForInput(buf, sizeof(buf));
  toLowerStr(buf);
  if (buf[0] == 'y') {
    Serial.print("Brightness (0-255): ");
    waitForInput(buf, sizeof(buf));
    return (uint8_t) constrain(atoi(buf), 0, 255);
  }
  return 255;
}

void handleDisplay(char* args) {
  uint8_t r, g, b;
  bool found = false;

  char lower[64];
  strncpy(lower, args, sizeof(lower) - 1);
  lower[sizeof(lower)-1] = '\0';
  toLowerStr(lower);

  // try named color
  for (int i = 0; i < defaultCount && !found; i++) {
    if (strcmp(lower, defaultColors[i].name) == 0) {
      r = defaultColors[i].r; g = defaultColors[i].g; b = defaultColors[i].b;
      found = true;
    }
  }
  for (int i = 0; i < customCount && !found; i++) {
    if (strcmp(lower, customColors[i].name) == 0) {
      r = customColors[i].r; g = customColors[i].g; b = customColors[i].b;
      found = true;
    }
  }

  // try hex or rgb()
  if (!found) found = parseColor(args, r, g, b);

  if (!found) {
    Serial.println("display error: color not recognised");
    return;
  }

  uint8_t bright = askBrightness();
  applyColor(r, g, b, bright);
}

void handleArray(char* args) {
  char buf[64];

  if (strcmp(args, "add") == 0) {
    if (customCount >= MAX_CUSTOM) { Serial.println("array error: storage full"); return; }
    Serial.print("Name: ");
    waitForInput(buf, sizeof(buf));
    NamedColor nc;
    strncpy(nc.name, buf, sizeof(nc.name) - 1);
    nc.name[sizeof(nc.name)-1] = '\0';

    Serial.print("Code (rgb(r g b) or #hex): ");
    waitForInput(buf, sizeof(buf));
    if (!parseColor(buf, nc.r, nc.g, nc.b)) { Serial.println("array error: invalid code"); return; }

    Serial.print("Want to set brightness for this color? Y/N: ");
    waitForInput(buf, sizeof(buf));
    toLowerStr(buf);
    if (buf[0] == 'y') {
      Serial.print("Brightness (0-255): ");
      waitForInput(buf, sizeof(buf));
      nc.brightness = (uint8_t) constrain(atoi(buf), 0, 255);
    } else {
      nc.brightness = 255;
    }

    customColors[customCount++] = nc;
    saveCustomColors();
    Serial.println("Color successfully attached");

  } else if (strcmp(args, "delete") == 0) {
    listAllColors();
    Serial.print("Number to delete: ");
    waitForInput(buf, sizeof(buf));
    int idx = atoi(buf);
    NamedColor* c = getColorByIndex(idx);
    if (!c) { Serial.println("array error: invalid number"); return; }
    if (idx < defaultCount) { Serial.println("array error: cannot delete default colors"); return; }
    char name[32];
    strncpy(name, c->name, sizeof(name));
    int ci = idx - defaultCount;
    for (int i = ci; i < customCount - 1; i++) customColors[i] = customColors[i+1];
    customCount--;
    saveCustomColors();
    Serial.print("Color: "); Serial.print(name);
    Serial.print(", Number "); Serial.print(idx); Serial.println(" was deleted");

  } else if (strcmp(args, "editcode") == 0) {
    listAllColors();
    Serial.print("Number to edit: ");
    waitForInput(buf, sizeof(buf));
    int idx = atoi(buf);
    NamedColor* c = getColorByIndex(idx);
    if (!c) { Serial.println("array error: invalid number"); return; }
    Serial.print("New code (rgb(r g b) or #hex): ");
    waitForInput(buf, sizeof(buf));
    uint8_t r, g, b;
    if (!parseColor(buf, r, g, b)) { Serial.println("array error: invalid code"); return; }
    c->r = r; c->g = g; c->b = b;
    if (idx >= defaultCount) saveCustomColors();
    Serial.print("Color: "); Serial.print(c->name);
    Serial.print(", Number "); Serial.print(idx);
    Serial.print(" was changed to ("); Serial.print(r); Serial.print(" "); Serial.print(g); Serial.print(" "); Serial.print(b); Serial.println(")");

  } else if (strcmp(args, "rename") == 0) {
    listAllColors();
    Serial.print("Number to rename: ");
    waitForInput(buf, sizeof(buf));
    int idx = atoi(buf);
    NamedColor* c = getColorByIndex(idx);
    if (!c) { Serial.println("array error: invalid number"); return; }
    Serial.print("New name: ");
    waitForInput(buf, sizeof(buf));
    strncpy(c->name, buf, sizeof(c->name) - 1);
    if (idx >= defaultCount) saveCustomColors();
    Serial.print("Color number "); Serial.print(idx); Serial.print(" was changed to: "); Serial.println(c->name);

  } else {
    Serial.println("unknown array function, check https://github.com/dmach7/Light-Control-Engine cli.md");
  }
}

void setup() {
  Serial.begin(115200);
  rgbLed.begin();
  rgbLed.clear();
  rgbLed.show();
  loadCustomColors();
  Serial.println("RGB LED Control");
  delay(500);
  Serial.println("Type /help for instructions");
}

void loop() {
  if (Serial.available() > 0) {
    char input[64];
    int len = Serial.readBytesUntil('\n', input, sizeof(input) - 1);
    input[len] = '\0';
    if (len > 0 && input[len-1] == '\r') input[--len] = '\0';

    if (strcmp(input, "/help") == 0) {
      Serial.println("Check the full CLI reference at: https://github.com/dmach7/Light-Control-Engine — navigate to cli.md in the main tree");

    } else if (strncmp(input, "display ", 8) == 0) {
      handleDisplay(input + 8);

    } else if (strncmp(input, "array ", 6) == 0) {
      char args[32];
      strncpy(args, input + 6, sizeof(args) - 1);
      toLowerStr(args);
      handleArray(args);

    } else {
      Serial.println("Not recognised");  // didnt understand input, i wanted to put "wat" on the output, but the society would judge me😪
    }

    while (Serial.available() > 0) Serial.read();
  }
}

// so i asked claude help to map all of the colors codes, so u don't really need to put the code in all of the colors, surely, you will have to search the internet if u want a flying chihuahua of the sahara desert blue, but the main colors are there
//u can still add colors just by following the pattern, so if u want to add the Goose Turd Green, just put the coma in the last array and add {"Goose Turd Green", 84, 255, 162, 255}
