//V2.0
// so i asked claude help to map all of the colors codes, so u don't really need to put the code in all of the colors, surely, you will have to search the internet if u want a flying chihuahua of the sahara desert blue, but the main colors are there
//u can still add colors just by following the pattern, so if u want to add the Goose Turd Green, just put the coma in the last array and add {"Goose Turd Green", 84, 255, 162, 255}

//V3.0
// the 3.0 code is almost all generated by claude, i'm sorry but i had no idea how to do that without it, don't judge me bro, i'm not god, genius or sum shi

//V4.0
// fades are a thing now: fade, fadeg, fades and stop. "fade red 1.5s" makes one, fadeg is the same with a gamma curve so it looks less like a light switch
// the fade runs in the background so the cli keeps working (fadeTick() sits inside readLine, don't ask), only stop cancels it and the led commands are locked till it ends
// fades live in flash like the custom colors, 30 max, saved by number
// brightness is GONE. all of it. it only gave me problems, the led sits at 255 forever, want it dimmer? use lower rgb values
// colors are {name, r, g, b} now, so that 4th number in the examples up there? delete it or it won't compile
// old saved colors (the ones with brightness) get converted on the first boot of 4.0, the brightness gets dropped, the colors stay
// claude did the heavy lifting again, same deal as 3.0, still not judging

#include <Adafruit_NeoPixel.h>
#include <Preferences.h>
#include <strings.h>

#define LED_PIN 48
#define LED_COUNT 1
#define MAX_FADES 30
#define MAX_TIME_MS 3600000UL // 1h, longest time u can type
#define FADE_GAMMA 2.2

Adafruit_NeoPixel rgbLed(LED_COUNT, LED_PIN, NEO_GRB + NEO_KHZ800);
Preferences prefs;

#define NAME_LEN 32

struct NamedColor {
  char name[NAME_LEN];
  uint8_t r, g, b;
};

// 3.0 layout, only here so the migration can read it
struct OldColor {
  char name[NAME_LEN];
  uint8_t r, g, b, brightness;
};

struct FadeSlot {
  uint32_t inMs, holdMs, outMs;
  uint8_t r, g, b, gamma, hasOut;
};

// default colors, always present
NamedColor defaultColors[] = {
  {"red", 255, 0, 0},
  {"green", 0, 255, 0},
  {"blue", 0, 0, 255},
  {"yellow", 255, 255, 0},
  {"cyan", 0, 255, 255},
  {"magenta", 255, 0, 255},
  {"white", 255, 255, 255},
  {"orange", 255, 165, 0},
  {"purple", 128, 0, 128}, // <--- just like this
  {"off", 0, 0, 0} //add a coma here if u want to add another default color
};

#define MAX_CUSTOM 20
NamedColor customColors[MAX_CUSTOM];
int customCount = 0;
int defaultCount = sizeof(defaultColors) / sizeof(defaultColors[0]);

FadeSlot fades[MAX_FADES];
int fadeCount = 0;

// the fade that is running right now (a copy, so editing/deleting the saved one can't mess it up)
bool fadeOn = false;
FadeSlot runFade;
uint32_t fadeT0 = 0;
uint8_t lastR = 0, lastG = 0, lastB = 0;
bool migrated = false; // converted 3.0 colors on this boot?

// what ask() gives back
#define IN_OK 0
#define IN_BACK 1 // typed "back", one step back
#define IN_ESC 2 // typed "esc", straight to the menu

void toLowerStr(char* str) {
  for (int i = 0; str[i]; i++) {
    if (str[i] >= 'A' && str[i] <= 'Z') str[i] += 32; //this block was a bitch to write, why so complicated, don't ask me how ts works
  }
}

void menu() {
  Serial.println("Type /help for instructions");
}

void applyColor(uint8_t r, uint8_t g, uint8_t b) {
  rgbLed.setPixelColor(0, rgbLed.Color(r, g, b));
  rgbLed.show();
}

// only pokes the led when the color actually changed
void ledSet(uint8_t r, uint8_t g, uint8_t b) {
  if (r == lastR && g == lastG && b == lastB) return;
  lastR = r; lastG = g; lastB = b;
  applyColor(r, g, b);
}

// called all the time from readLine, does one step of the running fade
void fadeTick() {
  if (!fadeOn) return;
  uint32_t t = millis() - fadeT0;
  uint32_t inEnd = runFade.inMs;
  uint32_t holdEnd = inEnd + runFade.holdMs;
  uint32_t outEnd = holdEnd + runFade.outMs;
  float lvl;
  if (t < inEnd) lvl = (float) t / runFade.inMs;
  else if (t < holdEnd) lvl = 1.0f;
  else if (runFade.hasOut && t < outEnd) lvl = 1.0f - (float) (t - holdEnd) / runFade.outMs;
  else { // done, no fade out means instant off. prints nothing
    fadeOn = false;
    applyColor(0, 0, 0);
    return;
  }
  if (runFade.gamma) lvl = powf(lvl, FADE_GAMMA);
  ledSet((uint8_t) (runFade.r * lvl + 0.5f), (uint8_t) (runFade.g * lvl + 0.5f), (uint8_t) (runFade.b * lvl + 0.5f));
}

void startFade(const FadeSlot &f, int idx) {
  runFade = f;
  fadeT0 = millis();
  fadeOn = true;
  lastR = lastG = lastB = 0;
  applyColor(0, 0, 0); // always starts from black
  Serial.print("Running fade number "); Serial.println(idx);
}

// true = a fade is running, so the led is locked
bool busy() {
  fadeTick(); // so a fade that just ended doesn't count
  if (!fadeOn) return false;
  Serial.println("led busy: a fade is running, type stop to cancel it");
  return true;
}

void handleStop() {
  fadeTick();
  if (!fadeOn) { Serial.println("stop: nothing is running"); return; }
  fadeOn = false;
  applyColor(0, 0, 0);
  Serial.println("Fade stopped");
}

void saveCustomColors(); // used by loadCustomColors to self heal
void loadCustomColors() {
  prefs.begin("lce", false); // read only errors out on first boot, namespace doesn't exist yet
  int ver = prefs.getInt("ver", 0); // no ver = 3.0 or older, brightness in the layout
  int n = prefs.getInt("count", 0);
  customCount = constrain(n, 0, MAX_CUSTOM);
  for (int i = 0; i < customCount; i++) {
    char key[16];
    sprintf(key, "c%d", i);
    memset(&customColors[i], 0, sizeof(NamedColor));
    if (ver < 4) { // old layout, brightness gets dropped here
      OldColor old;
      memset(&old, 0, sizeof(old));
      prefs.getBytes(key, &old, sizeof(old));
      memcpy(customColors[i].name, old.name, NAME_LEN - 1);
      customColors[i].r = old.r;
      customColors[i].g = old.g;
      customColors[i].b = old.b;
    } else {
      prefs.getBytes(key, &customColors[i], sizeof(NamedColor));
    }
    customColors[i].name[NAME_LEN - 1] = '\0';
  }
  prefs.end();
  // toss any leftover entry with a blank name (stale/corrupted save from before), self healing
  int w = 0;
  for (int i = 0; i < customCount; i++) {
    if (customColors[i].name[0] != '\0') customColors[w++] = customColors[i];
  }
  bool healed = (w != customCount);
  customCount = w;
  if (ver < 4 && customCount > 0) migrated = true;
  if (ver < 4 || healed) saveCustomColors(); // rewrites everything in the 4.0 layout
}

void saveCustomColors() {
  prefs.begin("lce", false);
  prefs.putInt("ver", 4);
  prefs.putInt("count", customCount);
  for (int i = 0; i < customCount; i++) {
    char key[16];
    sprintf(key, "c%d", i);
    prefs.putBytes(key, &customColors[i], sizeof(NamedColor));
  }
  prefs.end();
}

void saveFades() {
  prefs.begin("lce", false);
  prefs.putInt("fcount", fadeCount);
  for (int i = 0; i < fadeCount; i++) {
    char key[16];
    sprintf(key, "f%d", i);
    prefs.putBytes(key, &fades[i], sizeof(FadeSlot));
  }
  prefs.end();
}

bool fadeValid(const FadeSlot &f) {
  if (f.inMs == 0 || f.inMs > MAX_TIME_MS || f.holdMs > MAX_TIME_MS) return false;
  if (f.hasOut > 1 || f.gamma > 1) return false;
  if (f.hasOut && (f.outMs == 0 || f.outMs > MAX_TIME_MS)) return false;
  return (f.r | f.g | f.b) != 0;
}

void loadFades() {
  prefs.begin("lce", false);
  int n = constrain(prefs.getInt("fcount", 0), 0, MAX_FADES);
  int w = 0;
  for (int i = 0; i < n; i++) {
    char key[16];
    sprintf(key, "f%d", i);
    FadeSlot f;
    memset(&f, 0, sizeof(f));
    size_t got = prefs.getBytes(key, &f, sizeof(f));
    if (got == sizeof(f) && fadeValid(f)) fades[w++] = f; // junk gets tossed
  }
  prefs.end();
  fadeCount = w;
  if (w != n) saveFades();
}

void listAllColors() {
  Serial.println("--- color list ---");
  for (int i = 0; i < defaultCount; i++) {
    Serial.print(i); Serial.print(". [default] "); Serial.println(defaultColors[i].name);
  }
  for (int i = 0; i < customCount; i++) {
    Serial.print(defaultCount + i); Serial.print(". "); Serial.println(customColors[i].name);
  }
  Serial.println("------------------");
}

void printTime(uint32_t ms) {
  if (ms % 1000 == 0) { Serial.print(ms / 1000); Serial.print("s"); }
  else { Serial.print(ms); Serial.print("ms"); }
}

void listFades() {
  Serial.println("--- fade list ---");
  for (int i = 0; i < fadeCount; i++) {
    FadeSlot* f = &fades[i];
    Serial.print(i); Serial.print(". ("); Serial.print(f->r); Serial.print(" "); Serial.print(f->g); Serial.print(" "); Serial.print(f->b);
    Serial.print(") "); Serial.print(f->gamma ? "gamma" : "linear");
    Serial.print(" | in "); printTime(f->inMs);
    Serial.print(" | hold "); printTime(f->holdMs);
    Serial.print(" | out ");
    if (f->hasOut) printTime(f->outMs); else Serial.print("none");
    Serial.println();
  }
  Serial.println("-----------------");
}

NamedColor* getColorByIndex(int idx) {
  if (idx < 0) return nullptr;
  if (idx < defaultCount) return &defaultColors[idx];
  idx -= defaultCount;
  if (idx < customCount) return &customColors[idx];
  return nullptr;
}

void setName(char* dst, const char* src) {
  strncpy(dst, src, NAME_LEN - 1);
  dst[NAME_LEN - 1] = '\0';
}

// ignore = index that can keep its own name (rename), -1 for none
bool nameTaken(const char* name, int ignore) {
  for (int i = 0; i < defaultCount + customCount; i++) {
    if (i == ignore) continue;
    if (strcasecmp(name, getColorByIndex(i)->name) == 0) return true;
  }
  return false;
}

// blocks until a full line arrives, works with \n, \r or both
void readLine(char* buf, int maxLen) {
  int len = 0;
  while (true) {
    while (Serial.available() == 0) { fadeTick(); delay(1); } // the fade keeps running while we wait
    char c = Serial.read();
    if (c == '\t') c = ' ';
    if (c == '\n' || c == '\r') {
      while (len > 0 && buf[len-1] == ' ') len--;
      if (len > 0) break; // empty lines (and the 2nd half of \r\n) get skipped
      continue;
    }
    if (len == 0 && c == ' ') continue;
    if (len < maxLen - 1) buf[len++] = c;
  }
  buf[len] = '\0';
}

int cmdType(const char* s) {
  if (strcasecmp(s, "back") == 0) return IN_BACK;
  if (strcasecmp(s, "esc") == 0) return IN_ESC;
  return IN_OK;
}

// prints the prompt, waits for the answer and echoes it
int ask(const char* prompt, char* buf, int maxLen) {
  Serial.print(prompt);
  readLine(buf, maxLen);
  Serial.println(buf);
  return cmdType(buf);
}

int askYN(const char* prompt, bool &yes) {
  char buf[8];
  while (true) {
    int s = ask(prompt, buf, sizeof(buf));
    if (s != IN_OK) return s;
    toLowerStr(buf);
    if (strcmp(buf, "y") == 0) { yes = true; return IN_OK; }
    if (strcmp(buf, "n") == 0) { yes = false; return IN_OK; }
    Serial.println("type y or n");
  }
}

int askNumber(const char* prompt, int &val) {
  char buf[16];
  while (true) {
    int s = ask(prompt, buf, sizeof(buf));
    if (s != IN_OK) return s;
    char* end;
    long n = strtol(buf, &end, 10);
    if (*end == '\0') { val = (int) n; return IN_OK; }
    Serial.println("type a number");
  }
}

// only lets custom colors through, defaults live in the code
int askCustomIndex(const char* prompt, int &idx) {
  while (true) {
    int s = askNumber(prompt, idx);
    if (s != IN_OK) return s;
    if (idx < 0 || idx >= defaultCount + customCount) { Serial.println("array error: invalid number"); continue; }
    if (idx < defaultCount) { Serial.println("array error: default colors are locked, edit them in the code"); continue; }
    return IN_OK;
  }
}

int askFadeIndex(const char* prompt, int &idx) {
  while (true) {
    int s = askNumber(prompt, idx);
    if (s != IN_OK) return s;
    if (idx < 0 || idx >= fadeCount) { Serial.println("fades error: invalid number"); continue; }
    return IN_OK;
  }
}

// handles back/esc, false = leave the process
bool nav(int s, int &step) {
  if (s == IN_ESC || (s == IN_BACK && step == 0)) { menu(); return false; }
  if (s == IN_BACK) step--;
  return true;
}

bool noCustom() {
  if (customCount > 0) return false;
  Serial.println("array error: no custom colors yet");
  return true;
}

bool noFades() {
  if (fadeCount > 0) return false;
  Serial.println("fades error: no fades saved yet");
  return true;
}

bool parseColor(const char* input, uint8_t &r, uint8_t &g, uint8_t &b) {
  // hex
  if (input[0] == '#') {
    unsigned int ri, gi, bi;
    if (strlen(input) == 7 && sscanf(input + 1, "%2x%2x%2x", &ri, &gi, &bi) == 3) {
      r = ri; g = gi; b = bi;
      return true;
    }
    return false;
  }
  // rgb(r g b), commas work too
  if (strncasecmp(input, "rgb(", 4) == 0) {
    int ri, gi, bi;
    if (sscanf(input + 4, "%d%*[ ,]%d%*[ ,]%d", &ri, &gi, &bi) == 3) {
      r = constrain(ri, 0, 255);
      g = constrain(gi, 0, 255);
      b = constrain(bi, 0, 255);
      return true;
    }
    return false;
  }
  return false;
}

// name first, then hex or rgb()
bool findColor(const char* name, uint8_t &r, uint8_t &g, uint8_t &b) {
  for (int i = 0; i < defaultCount + customCount; i++) {
    NamedColor* c = getColorByIndex(i);
    if (strcasecmp(name, c->name) == 0) {
      r = c->r; g = c->g; b = c->b;
      return true;
    }
  }
  return parseColor(name, r, g, b);
}

// needs a suffix, 1.5s or 1500ms. 0 = ok, 1 = bad format, 2 = too long
int parseTime(const char* s, uint32_t &ms) {
  if (!isdigit((unsigned char) s[0]) && s[0] != '.') return 1;
  char* end;
  double v = strtod(s, &end);
  if (strcasecmp(end, "ms") == 0) v *= 1;
  else if (strcasecmp(end, "s") == 0) v *= 1000;
  else return 1; // no suffix = error
  if (!(v >= 0) || v > MAX_TIME_MS) return 2;
  ms = (uint32_t) (v + 0.5);
  return 0;
}

bool timeOk(const char* s, uint32_t &ms, bool zeroOk) {
  int e = parseTime(s, ms);
  if (e == 1) { Serial.println("fade error: invalid time, use a suffix like 1.5s or 1500ms"); return false; }
  if (e == 2) { Serial.print("fade error: time too long, max is "); Serial.print(MAX_TIME_MS / 1000); Serial.println("s"); return false; }
  if (ms == 0 && !zeroOk) { Serial.println("fade error: time can't be 0"); return false; }
  return true;
}

void factoryReset() {
  if (busy()) return;
  bool yes;
  Serial.println("This deletes ALL saved colors and fades and puts everything back to factory");
  int s = askYN("Are you sure? Y/N: ", yes);
  if (s != IN_OK) { menu(); return; }
  if (!yes) { Serial.println("Cancelled"); return; }
  prefs.begin("lce", false);
  prefs.clear();
  prefs.end();
  customCount = 0;
  fadeCount = 0;
  rgbLed.clear();
  rgbLed.show();
  Serial.println("Memory wiped, back to factory");
}

void handleDisplay(char* args) {
  uint8_t r, g, b;
  if (busy()) return;
  if (args[0] == '\0') { Serial.println("display error: missing color"); return; }
  if (cmdType(args) != IN_OK) { menu(); return; }
  if (!findColor(args, r, g, b)) {
    Serial.println("display error: color not recognised");
    return;
  }
  applyColor(r, g, b);
}

void arrayAdd() {
  if (customCount >= MAX_CUSTOM) { Serial.println("array error: storage full"); return; }
  char buf[64];
  NamedColor nc;
  memset(&nc, 0, sizeof(nc));
  int step = 0;
  while (true) {
    int s;
    if (step == 0) {
      s = ask("Name: ", buf, sizeof(buf));
      if (s == IN_OK) {
        setName(nc.name, buf);
        if (nameTaken(nc.name, -1)) { Serial.println("array error: name already in use"); continue; }
        step = 1;
      }
    } else {
      s = ask("Code (rgb(r g b) or #hex): ", buf, sizeof(buf));
      if (s == IN_OK) {
        if (!parseColor(buf, nc.r, nc.g, nc.b)) { Serial.println("array error: invalid code"); continue; }
        break;
      }
    }
    if (!nav(s, step)) return;
  }
  customColors[customCount++] = nc;
  saveCustomColors();
  Serial.println("Color successfully attached");
}

void arrayDelete() {
  if (noCustom()) return;
  int idx;
  listAllColors();
  int s = askCustomIndex("Number to delete: ", idx);
  if (s != IN_OK) { menu(); return; }
  char name[NAME_LEN];
  int ci = idx - defaultCount;
  setName(name, customColors[ci].name);
  for (int i = ci; i < customCount - 1; i++) customColors[i] = customColors[i+1];
  customCount--;
  saveCustomColors();
  Serial.print("Color: "); Serial.print(name);
  Serial.print(", Number "); Serial.print(idx); Serial.println(" was deleted");
}

void arrayEditCode() {
  if (noCustom()) return;
  char buf[64];
  int idx;
  uint8_t r, g, b;
  listAllColors();
  int step = 0;
  while (true) {
    int s;
    if (step == 0) {
      s = askCustomIndex("Number to edit: ", idx);
      if (s == IN_OK) step = 1;
    } else {
      s = ask("New code (rgb(r g b) or #hex): ", buf, sizeof(buf));
      if (s == IN_OK) {
        if (!parseColor(buf, r, g, b)) { Serial.println("array error: invalid code"); continue; }
        break;
      }
    }
    if (!nav(s, step)) return;
  }
  NamedColor* c = &customColors[idx - defaultCount];
  c->r = r; c->g = g; c->b = b;
  saveCustomColors();
  Serial.print("Color: "); Serial.print(c->name);
  Serial.print(", Number "); Serial.print(idx);
  Serial.print(" was changed to ("); Serial.print(r); Serial.print(" "); Serial.print(g); Serial.print(" "); Serial.print(b); Serial.println(")");
}

void arrayRename() {
  if (noCustom()) return;
  char buf[64];
  char nm[NAME_LEN];
  int idx;
  listAllColors();
  int step = 0;
  while (true) {
    int s;
    if (step == 0) {
      s = askCustomIndex("Number to rename: ", idx);
      if (s == IN_OK) step = 1;
    } else {
      s = ask("New name: ", buf, sizeof(buf));
      if (s == IN_OK) {
        setName(nm, buf);
        if (nameTaken(nm, idx)) { Serial.println("array error: name already in use"); continue; }
        break;
      }
    }
    if (!nav(s, step)) return;
  }
  setName(customColors[idx - defaultCount].name, nm);
  saveCustomColors();
  Serial.print("Color number "); Serial.print(idx); Serial.print(" was changed to: "); Serial.println(nm);
}

void handleArray(char* args) {
  if (strcmp(args, "add") == 0) {
    arrayAdd();
  } else if (strcmp(args, "delete all") == 0) {
    factoryReset();
  } else if (strcmp(args, "delete") == 0) {
    arrayDelete();
  } else if (strcmp(args, "editcode") == 0) {
    arrayEditCode();
  } else if (strcmp(args, "rename") == 0) {
    arrayRename();
  } else if (cmdType(args) != IN_OK) {
    menu();
  } else {
    Serial.println("unknown array function, check https://github.com/dmach7/Light-Control-Engine cli.md");
  }
}

// fade [color] [fade in time], last space splits, everything before it is the color
void handleFade(char* args, bool gamma) {
  uint8_t r, g, b;
  if (busy()) return;
  if (args[0] == '\0') { Serial.println("fade error: missing color and time"); return; }
  if (cmdType(args) != IN_OK) { menu(); return; }
  if (fadeCount >= MAX_FADES) { Serial.println("fade error: storage full"); return; }
  bool wholeColor = findColor(args, r, g, b); // whole line is a color = the time is missing
  char* sp = strrchr(args, ' ');
  if (!sp) { Serial.println(wholeColor ? "fade error: missing fade in time" : "fade error: color not recognised"); return; }
  *sp = '\0';
  char* tstr = sp + 1;
  int len = strlen(args);
  while (len > 0 && args[len-1] == ' ') args[--len] = '\0';
  if (!findColor(args, r, g, b)) { Serial.println(wholeColor ? "fade error: missing fade in time" : "fade error: color not recognised"); return; }
  if ((r | g | b) == 0) { Serial.println("fade error: can't fade to black, pick another color"); return; }
  FadeSlot nf;
  memset(&nf, 0, sizeof(nf));
  if (!timeOk(tstr, nf.inMs, false)) return;
  nf.r = r; nf.g = g; nf.b = b;
  nf.gamma = gamma ? 1 : 0;
  char buf[32];
  int step = 0;
  while (true) {
    bool yes;
    int s;
    if (step == 0) {
      s = ask("Hold time (how long it stays lit, e.g. 2s): ", buf, sizeof(buf));
      if (s == IN_OK) {
        if (!timeOk(buf, nf.holdMs, true)) continue;
        step = 1;
      }
    } else if (step == 1) {
      s = askYN("Add fade out? Y/N: ", yes);
      if (s == IN_OK) {
        if (!yes) { nf.hasOut = 0; nf.outMs = 0; break; }
        step = 2;
      }
    } else {
      s = ask("Fade out time: ", buf, sizeof(buf));
      if (s == IN_OK) {
        if (!timeOk(buf, nf.outMs, false)) continue;
        nf.hasOut = 1;
        break;
      }
    }
    if (!nav(s, step)) return;
  }
  fades[fadeCount++] = nf;
  int idx = fadeCount - 1;
  saveFades();
  if (nf.hasOut) { Serial.print("fade successfully created, saved by number "); Serial.println(idx); }
  else { Serial.print("fade successfully created as number "); Serial.println(idx); }
  bool yes;
  int s = askYN("Execute now? Y/N: ", yes);
  if (s != IN_OK) { menu(); return; }
  if (yes) startFade(nf, idx);
}

// -1 = bad number, 0 = nothing typed (ask for it), 1 = got it
int fadeArg(const char* s, int &idx) {
  if (s[0] == '\0') return 0;
  char* end;
  long n = strtol(s, &end, 10);
  if (*end != '\0' || n < 0 || n >= fadeCount) { Serial.println("fades error: invalid number"); return -1; }
  idx = (int) n;
  return 1;
}

void fadesRun(char* rest) {
  if (busy()) return;
  if (noFades()) return;
  int idx = -1;
  int a = fadeArg(rest, idx);
  if (a < 0) return;
  if (a == 0) {
    listFades();
    int s = askFadeIndex("Number to run: ", idx);
    if (s != IN_OK) { menu(); return; }
  }
  startFade(fades[idx], idx);
}

void fadesDelete(char* rest) {
  if (noFades()) return;
  int idx = -1;
  int a = fadeArg(rest, idx);
  if (a < 0) return;
  if (a == 0) {
    listFades();
    int s = askFadeIndex("Number to delete: ", idx);
    if (s != IN_OK) { menu(); return; }
  }
  for (int i = idx; i < fadeCount - 1; i++) fades[i] = fades[i+1];
  fadeCount--;
  saveFades();
  Serial.print("Fade number "); Serial.print(idx); Serial.println(" was deleted");
}

void fadesEdit(char* rest) {
  if (noFades()) return;
  int idx = -1;
  int a = fadeArg(rest, idx);
  if (a < 0) return;
  if (a == 0) listFades();
  char buf[64];
  char field[16];
  uint8_t r = 0, g = 0, b = 0;
  uint32_t ms = 0;
  bool remove = false;
  int step = (a == 1) ? 1 : 0;
  while (true) {
    int s;
    if (step == 0) {
      s = askFadeIndex("Number to edit: ", idx);
      if (s == IN_OK) step = 1;
    } else if (step == 1) {
      s = ask("Edit what? (color, in, hold, out): ", field, sizeof(field));
      if (s == IN_OK) {
        toLowerStr(field);
        if (strcmp(field, "color") && strcmp(field, "in") && strcmp(field, "hold") && strcmp(field, "out")) {
          Serial.println("fades error: type color, in, hold or out");
          continue;
        }
        step = 2;
      }
    } else {
      if (strcmp(field, "color") == 0) {
        s = ask("New color (name, rgb(r g b) or #hex): ", buf, sizeof(buf));
        if (s == IN_OK) {
          if (!findColor(buf, r, g, b)) { Serial.println("fade error: color not recognised"); continue; }
          if ((r | g | b) == 0) { Serial.println("fade error: can't fade to black, pick another color"); continue; }
          break;
        }
      } else if (strcmp(field, "out") == 0) {
        s = ask("New fade out time (or none to remove it): ", buf, sizeof(buf));
        if (s == IN_OK) {
          toLowerStr(buf);
          if (strcmp(buf, "none") == 0) { remove = true; break; }
          if (!timeOk(buf, ms, false)) continue;
          break;
        }
      } else {
        s = ask(strcmp(field, "in") == 0 ? "New fade in time: " : "New hold time: ", buf, sizeof(buf));
        if (s == IN_OK) {
          if (!timeOk(buf, ms, strcmp(field, "hold") == 0)) continue;
          break;
        }
      }
    }
    if (!nav(s, step)) return;
  }
  FadeSlot* f = &fades[idx];
  Serial.print("Fade number "); Serial.print(idx);
  if (strcmp(field, "color") == 0) {
    f->r = r; f->g = g; f->b = b;
    Serial.print(": color was changed to ("); Serial.print(r); Serial.print(" "); Serial.print(g); Serial.print(" "); Serial.print(b); Serial.println(")");
  } else if (strcmp(field, "out") == 0) {
    if (remove) { f->hasOut = 0; f->outMs = 0; Serial.println(": fade out was removed"); }
    else { f->hasOut = 1; f->outMs = ms; Serial.print(": fade out was changed to "); printTime(ms); Serial.println(); }
  } else if (strcmp(field, "in") == 0) {
    f->inMs = ms;
    Serial.print(": fade in was changed to "); printTime(ms); Serial.println();
  } else {
    f->holdMs = ms;
    Serial.print(": hold was changed to "); printTime(ms); Serial.println();
  }
  saveFades();
}

void handleFades(char* args) {
  char* rest = strchr(args, ' ');
  if (rest) {
    *rest++ = '\0';
    while (*rest == ' ') rest++;
  } else {
    rest = args + strlen(args);
  }
  toLowerStr(args);
  if (strcmp(args, "list") == 0) {
    if (!noFades()) listFades();
  } else if (strcmp(args, "run") == 0) {
    fadesRun(rest);
  } else if (strcmp(args, "delete") == 0) {
    fadesDelete(rest);
  } else if (strcmp(args, "edit") == 0) {
    fadesEdit(rest);
  } else if (cmdType(args) != IN_OK) {
    menu();
  } else {
    Serial.println("unknown fades function, check https://github.com/dmach7/Light-Control-Engine cli.md");
  }
}

void setup() {
  Serial.begin(115200);
  rgbLed.begin();
  rgbLed.setBrightness(255); // fixed, brightness is gone
  rgbLed.clear();
  rgbLed.show();
  loadCustomColors();
  loadFades();
  Serial.println("RGB LED Control");
  if (migrated) Serial.println("saved colors converted to the 4.0 layout, brightness dropped");
  delay(500);
  menu();
}

void loop() {
  char input[64];
  Serial.print("> ");
  readLine(input, sizeof(input));
  Serial.println(input);
  // splits "cmd args", only the cmd gets lowercased here
  char* args = strchr(input, ' ');
  if (args) {
    *args++ = '\0';
    while (*args == ' ') args++;
  } else {
    args = input + strlen(input);
  }
  toLowerStr(input);
  if (strcmp(input, "/help") == 0) {
    Serial.println("Check the full CLI reference at: https://github.com/dmach7/Light-Control-Engine — navigate to cli.md in the main tree");
  } else if (strcmp(input, "display") == 0) {
    handleDisplay(args);
  } else if (strcmp(input, "fade") == 0) {
    handleFade(args, false);
  } else if (strcmp(input, "fadeg") == 0) {
    handleFade(args, true);
  } else if (strcmp(input, "fades") == 0) {
    handleFades(args);
  } else if (strcmp(input, "stop") == 0) {
    handleStop();
  } else if (strcmp(input, "array") == 0) {
    toLowerStr(args);
    handleArray(args);
  } else if (strcmp(input, "delete") == 0 && strcasecmp(args, "all") == 0) {
    factoryReset();
  } else if (cmdType(input) != IN_OK) {
    menu();
  } else {
    Serial.println("Not recognised"); // didnt understand input, i wanted to put "wat" on the output, but the society would judge me😪
  }
}
