//V2.0
// so i asked claude help to map all of the colors codes, so u don't really need to put the code in all of the colors, surely, you will have to search the internet if u want a flying chihuahua of the sahara desert blue, but the main colors are there
//u can still add colors just by following the pattern, so if u want to add the Goose Turd Green, just put the coma in the last array and add {"Goose Turd Green", 84, 255, 162, 255}
//V3.0
// the 3.0 code is almost all generated by claude, i'm sorry but i had no idea how to do that without it, don't judge me bro, i'm not god, genius or sum shi


#include <Adafruit_NeoPixel.h>
#include <Preferences.h>
#include <strings.h>

#define LED_PIN 48
#define LED_COUNT 1

Adafruit_NeoPixel rgbLed(LED_COUNT, LED_PIN, NEO_GRB + NEO_KHZ800);
Preferences prefs;

#define NAME_LEN 32

struct NamedColor {
  char name[NAME_LEN];
  uint8_t r, g, b, brightness;
};

// default colors, always present
NamedColor defaultColors[] = {
  {"red",     255, 0,   0,   255},
  {"green",   0,   255, 0,   255},
  {"blue",    0,   0,   255, 255},
  {"yellow",  255, 255, 0,   255},
  {"cyan",    0,   255, 255, 255},
  {"magenta", 255, 0,   255, 255},
  {"white",   255, 255, 255, 255},
  {"orange",  255, 165, 0,   255},
  {"purple",  128, 0,   128, 255},  // <--- just like this
  {"off",     0,   0,   0,   255}   //add a coma here if u want to add another default color
};

#define MAX_CUSTOM 20
NamedColor customColors[MAX_CUSTOM];
int customCount = 0;

int defaultCount = sizeof(defaultColors) / sizeof(defaultColors[0]);

// what ask() gives back
#define IN_OK   0
#define IN_BACK 1  // typed "back", one step back
#define IN_ESC  2  // typed "esc", straight to the menu

void toLowerStr(char* str) {
  for (int i = 0; str[i]; i++) {
    if (str[i] >= 'A' && str[i] <= 'Z') str[i] += 32;  //this block was a bitch to write, why so complicated, don't ask me how ts works
  }
}

void menu() {
  Serial.println("Type /help for instructions");
}

void applyColor(uint8_t r, uint8_t g, uint8_t b, uint8_t bright) {
  rgbLed.setBrightness(bright);
  rgbLed.setPixelColor(0, rgbLed.Color(r, g, b));
  rgbLed.show();
}

void saveCustomColors();  // used by loadCustomColors to self heal

void loadCustomColors() {
  prefs.begin("lce", false);  // read only errors out on first boot, namespace doesn't exist yet
  int n = prefs.getInt("count", 0);
  customCount = constrain(n, 0, MAX_CUSTOM);
  for (int i = 0; i < customCount; i++) {
    char key[16];
    sprintf(key, "c%d", i);
    prefs.getBytes(key, &customColors[i], sizeof(NamedColor));
  }
  prefs.end();

  // toss any leftover entry with a blank name (stale/corrupted save from before), self healing
  int w = 0;
  for (int i = 0; i < customCount; i++) {
    if (customColors[i].name[0] != '\0') customColors[w++] = customColors[i];
  }
  if (w != customCount) {
    customCount = w;
    saveCustomColors();
  }
}

void saveCustomColors() {
  prefs.begin("lce", false);
  prefs.putInt("count", customCount);
  for (int i = 0; i < customCount; i++) {
    char key[16];
    sprintf(key, "c%d", i);
    prefs.putBytes(key, &customColors[i], sizeof(NamedColor));
  }
  prefs.end();
}

void listAllColors() {
  Serial.println("--- color list ---");
  for (int i = 0; i < defaultCount; i++) {
    Serial.print(i); Serial.print(". [default] "); Serial.println(defaultColors[i].name);
  }
  for (int i = 0; i < customCount; i++) {
    Serial.print(defaultCount + i); Serial.print(". "); Serial.println(customColors[i].name);
  }
  Serial.println("------------------");
}

NamedColor* getColorByIndex(int idx) {
  if (idx < 0) return nullptr;
  if (idx < defaultCount) return &defaultColors[idx];
  idx -= defaultCount;
  if (idx < customCount) return &customColors[idx];
  return nullptr;
}

void setName(char* dst, const char* src) {
  strncpy(dst, src, NAME_LEN - 1);
  dst[NAME_LEN - 1] = '\0';
}

// ignore = index that can keep its own name (rename), -1 for none
bool nameTaken(const char* name, int ignore) {
  for (int i = 0; i < defaultCount + customCount; i++) {
    if (i == ignore) continue;
    if (strcasecmp(name, getColorByIndex(i)->name) == 0) return true;
  }
  return false;
}

// blocks until a full line arrives, works with \n, \r or both
void readLine(char* buf, int maxLen) {
  int len = 0;
  while (true) {
    while (Serial.available() == 0) delay(1);
    char c = Serial.read();
    if (c == '\t') c = ' ';
    if (c == '\n' || c == '\r') {
      while (len > 0 && buf[len-1] == ' ') len--;
      if (len > 0) break;  // empty lines (and the 2nd half of \r\n) get skipped
      continue;
    }
    if (len == 0 && c == ' ') continue;
    if (len < maxLen - 1) buf[len++] = c;
  }
  buf[len] = '\0';
}

int cmdType(const char* s) {
  if (strcasecmp(s, "back") == 0) return IN_BACK;
  if (strcasecmp(s, "esc") == 0) return IN_ESC;
  return IN_OK;
}

// prints the prompt, waits for the answer and echoes it
int ask(const char* prompt, char* buf, int maxLen) {
  Serial.print(prompt);
  readLine(buf, maxLen);
  Serial.println(buf);
  return cmdType(buf);
}

int askYN(const char* prompt, bool &yes) {
  char buf[8];
  while (true) {
    int s = ask(prompt, buf, sizeof(buf));
    if (s != IN_OK) return s;
    toLowerStr(buf);
    if (strcmp(buf, "y") == 0) { yes = true; return IN_OK; }
    if (strcmp(buf, "n") == 0) { yes = false; return IN_OK; }
    Serial.println("type y or n");
  }
}

int askNumber(const char* prompt, int &val) {
  char buf[16];
  while (true) {
    int s = ask(prompt, buf, sizeof(buf));
    if (s != IN_OK) return s;
    char* end;
    long n = strtol(buf, &end, 10);
    if (*end == '\0') { val = (int) n; return IN_OK; }
    Serial.println("type a number");
  }
}

// only lets custom colors through, defaults live in the code
int askCustomIndex(const char* prompt, int &idx) {
  while (true) {
    int s = askNumber(prompt, idx);
    if (s != IN_OK) return s;
    if (idx < 0 || idx >= defaultCount + customCount) { Serial.println("array error: invalid number"); continue; }
    if (idx < defaultCount) { Serial.println("array error: default colors are locked, edit them in the code"); continue; }
    return IN_OK;
  }
}

// handles back/esc, false = leave the process
bool nav(int s, int &step) {
  if (s == IN_ESC || (s == IN_BACK && step == 0)) { menu(); return false; }
  if (s == IN_BACK) step--;
  return true;
}

bool noCustom() {
  if (customCount > 0) return false;
  Serial.println("array error: no custom colors yet");
  return true;
}

bool parseColor(const char* input, uint8_t &r, uint8_t &g, uint8_t &b) {
  // hex
  if (input[0] == '#') {
    unsigned int ri, gi, bi;
    if (strlen(input) == 7 && sscanf(input + 1, "%2x%2x%2x", &ri, &gi, &bi) == 3) {
      r = ri; g = gi; b = bi;
      return true;
    }
    return false;
  }
  // rgb(r g b), commas work too
  if (strncasecmp(input, "rgb(", 4) == 0) {
    int ri, gi, bi;
    if (sscanf(input + 4, "%d%*[ ,]%d%*[ ,]%d", &ri, &gi, &bi) == 3) {
      r = constrain(ri, 0, 255);
      g = constrain(gi, 0, 255);
      b = constrain(bi, 0, 255);
      return true;
    }
    return false;
  }
  return false;
}

// name first, then hex or rgb(). named colors bring their own brightness
bool findColor(const char* name, uint8_t &r, uint8_t &g, uint8_t &b, uint8_t &bright) {
  for (int i = 0; i < defaultCount + customCount; i++) {
    NamedColor* c = getColorByIndex(i);
    if (strcasecmp(name, c->name) == 0) {
      r = c->r; g = c->g; b = c->b; bright = c->brightness;
      return true;
    }
  }
  bright = 255;
  return parseColor(name, r, g, b);
}

void factoryReset() {
  bool yes;
  Serial.println("This deletes ALL saved colors and puts everything back to factory");
  int s = askYN("Are you sure? Y/N: ", yes);
  if (s != IN_OK) { menu(); return; }
  if (!yes) { Serial.println("Cancelled"); return; }
  prefs.begin("lce", false);
  prefs.clear();
  prefs.end();
  customCount = 0;
  rgbLed.clear();
  rgbLed.show();
  Serial.println("Memory wiped, back to factory");
}

void handleDisplay(char* args) {
  uint8_t r, g, b, bright;

  if (args[0] == '\0') { Serial.println("display error: missing color"); return; }
  if (cmdType(args) != IN_OK) { menu(); return; }
  if (!findColor(args, r, g, b, bright)) {
    Serial.println("display error: color not recognised");
    return;
  }

  if (r == 0 && g == 0 && b == 0) {  // black is black no matter the brightness, don't bother asking
    applyColor(r, g, b, bright);
    return;
  }

  int step = 0;
  while (true) {
    bool yes;
    int n;
    int s;
    if (step == 0) {
      s = askYN("Want to define brightness? Y/N: ", yes);
      if (s == IN_OK) {
        if (!yes) break;
        step = 1;
      }
    } else {
      s = askNumber("Brightness (0-255): ", n);
      if (s == IN_OK) {
        bright = constrain(n, 0, 255);
        break;
      }
    }
    if (!nav(s, step)) return;
  }
  applyColor(r, g, b, bright);
}

void arrayAdd() {
  if (customCount >= MAX_CUSTOM) { Serial.println("array error: storage full"); return; }
  char buf[64];
  NamedColor nc;
  memset(&nc, 0, sizeof(nc));
  nc.brightness = 255;

  int step = 0;
  while (true) {
    bool yes;
    int n;
    int s;
    if (step == 0) {
      s = ask("Name: ", buf, sizeof(buf));
      if (s == IN_OK) {
        setName(nc.name, buf);
        if (nameTaken(nc.name, -1)) { Serial.println("array error: name already in use"); continue; }
        step = 1;
      }
    } else if (step == 1) {
      s = ask("Code (rgb(r g b) or #hex): ", buf, sizeof(buf));
      if (s == IN_OK) {
        if (!parseColor(buf, nc.r, nc.g, nc.b)) { Serial.println("array error: invalid code"); continue; }
        step = 2;
      }
    } else if (step == 2) {
      s = askYN("Want to set brightness for this color? Y/N: ", yes);
      if (s == IN_OK) {
        if (!yes) { nc.brightness = 255; break; }
        step = 3;
      }
    } else {
      s = askNumber("Brightness (0-255): ", n);
      if (s == IN_OK) {
        nc.brightness = constrain(n, 0, 255);
        break;
      }
    }
    if (!nav(s, step)) return;
  }

  customColors[customCount++] = nc;
  saveCustomColors();
  Serial.println("Color successfully attached");
}

void arrayDelete() {
  if (noCustom()) return;
  int idx;
  listAllColors();
  int s = askCustomIndex("Number to delete: ", idx);
  if (s != IN_OK) { menu(); return; }

  char name[NAME_LEN];
  int ci = idx - defaultCount;
  setName(name, customColors[ci].name);
  for (int i = ci; i < customCount - 1; i++) customColors[i] = customColors[i+1];
  customCount--;
  saveCustomColors();
  Serial.print("Color: "); Serial.print(name);
  Serial.print(", Number "); Serial.print(idx); Serial.println(" was deleted");
}

void arrayEditCode() {
  if (noCustom()) return;
  char buf[64];
  int idx;
  uint8_t r, g, b;
  listAllColors();

  int step = 0;
  while (true) {
    int s;
    if (step == 0) {
      s = askCustomIndex("Number to edit: ", idx);
      if (s == IN_OK) step = 1;
    } else {
      s = ask("New code (rgb(r g b) or #hex): ", buf, sizeof(buf));
      if (s == IN_OK) {
        if (!parseColor(buf, r, g, b)) { Serial.println("array error: invalid code"); continue; }
        break;
      }
    }
    if (!nav(s, step)) return;
  }

  NamedColor* c = &customColors[idx - defaultCount];
  c->r = r; c->g = g; c->b = b;
  saveCustomColors();
  Serial.print("Color: "); Serial.print(c->name);
  Serial.print(", Number "); Serial.print(idx);
  Serial.print(" was changed to ("); Serial.print(r); Serial.print(" "); Serial.print(g); Serial.print(" "); Serial.print(b); Serial.println(")");
}

void arrayRename() {
  if (noCustom()) return;
  char buf[64];
  char nm[NAME_LEN];
  int idx;
  listAllColors();

  int step = 0;
  while (true) {
    int s;
    if (step == 0) {
      s = askCustomIndex("Number to rename: ", idx);
      if (s == IN_OK) step = 1;
    } else {
      s = ask("New name: ", buf, sizeof(buf));
      if (s == IN_OK) {
        setName(nm, buf);
        if (nameTaken(nm, idx)) { Serial.println("array error: name already in use"); continue; }
        break;
      }
    }
    if (!nav(s, step)) return;
  }

  setName(customColors[idx - defaultCount].name, nm);
  saveCustomColors();
  Serial.print("Color number "); Serial.print(idx); Serial.print(" was changed to: "); Serial.println(nm);
}

void handleArray(char* args) {
  if (strcmp(args, "add") == 0) {
    arrayAdd();
  } else if (strcmp(args, "delete all") == 0) {
    factoryReset();
  } else if (strcmp(args, "delete") == 0) {
    arrayDelete();
  } else if (strcmp(args, "editcode") == 0) {
    arrayEditCode();
  } else if (strcmp(args, "rename") == 0) {
    arrayRename();
  } else if (cmdType(args) != IN_OK) {
    menu();
  } else {
    Serial.println("unknown array function, check https://github.com/dmach7/Light-Control-Engine cli.md");
  }
}

void setup() {
  Serial.begin(115200);
  rgbLed.begin();
  rgbLed.clear();
  rgbLed.show();
  loadCustomColors();
  Serial.println("RGB LED Control");
  delay(500);
  menu();
}

void loop() {
  char input[64];
  Serial.print("> ");
  readLine(input, sizeof(input));
  Serial.println(input);

  // splits "cmd args", only the cmd gets lowercased here
  char* args = strchr(input, ' ');
  if (args) {
    *args++ = '\0';
    while (*args == ' ') args++;
  } else {
    args = input + strlen(input);
  }
  toLowerStr(input);

  if (strcmp(input, "/help") == 0) {
    Serial.println("Check the full CLI reference at: https://github.com/dmach7/Light-Control-Engine — navigate to cli.md in the main tree");

  } else if (strcmp(input, "display") == 0) {
    handleDisplay(args);

  } else if (strcmp(input, "array") == 0) {
    toLowerStr(args);
    handleArray(args);

  } else if (strcmp(input, "delete") == 0 && strcasecmp(args, "all") == 0) {
    factoryReset();

  } else if (cmdType(input) != IN_OK) {
    menu();

  } else {
    Serial.println("Not recognised");  // didnt understand input, i wanted to put "wat" on the output, but the society would judge me😪
  }
}

// so i asked claude help to map all of the colors codes, so u don't really need to put the code in all of the colors, surely, you will have to search the internet if u want a flying chihuahua of the sahara desert blue, but the main colors are there
//u can still add colors just by following the pattern, so if u want to add the Goose Turd Green, just put the coma in the last array and add {"Goose Turd Green", 84, 255, 162, 255}
